Repository TEAM-INFINITE/Dawn-WithMe, pull requests merged in 2022-12, with the labels that each got.

#13 Feature/login 로그인 화면 및 기능 구현 #9
  .eslintrc.js
  package-lock.json
  package.json
  src/App.jsx
  src/api/axios-api.js
  src/api/login/postUserLogin.js
  src/assets/images/title-logo.png
  src/components/atoms/Button/Button.jsx
  src/components/atoms/Img/Img.jsx
  src/components/atoms/Input/TextFiled/TextFiled.jsx
  src/components/atoms/Label/TextLabel.jsx/TextLabel.jsx.jsx
  src/components/molecules/TextFiledCard/TextFiledCard.jsx
  src/components/molecules/TextFiledCard/styled.jsx
  src/components/organisms/LoginForm/LoginForm.jsx
  src/components/organisms/LoginForm/styled.jsx
  src/components/template/LoginTemplate/LoginTemplate.jsx
  src/components/template/LoginTemplate/styled.jsx
  src/pages/Login/Login.jsx
  src/styles/Globalstyled.jsx
  src/styles/theme.js
Labels: 기능구현, React, 스타일링, 레이아웃

#17 Feature/자유게시판 레이아웃&css 구현
  src/App.jsx
  src/assets/images/img-board.jpeg
  src/components/molecules/FeedCont/FeedCont.jsx
  src/components/molecules/FeedCont/styled.jsx
  src/components/molecules/FeedMoreIcon/FeedMoreIcon.jsx
  src/components/molecules/FeedMoreIcon/styled.jsx
  src/components/molecules/TopNavBar/TopNavBar.jsx
  src/components/molecules/TopNavBar/styled.jsx
  src/components/molecules/UserProfile/UserProfile.jsx
  src/components/molecules/UserProfile/UserProfileMore.jsx
  src/components/molecules/UserProfile/styled.jsx
  src/components/organisms/FeedCard/FeedCard.jsx
  src/components/organisms/FeedCard/styled.jsx
  src/components/template/FeedTemplate/FeedTemplate.jsx
  src/components/template/FeedTemplate/styled.jsx
  src/pages/FreeBoardPage/FreeBoardPage.jsx
Labels: 스타일링, 레이아웃

#18 Feature/메인홈및카테고리게시판
  .gitattributes
  src/App.jsx
  src/api/following/getFollowingList.js
  src/api/following/getFollowingProduct.js
  src/assets/images/icon-home-fill.png
  src/assets/images/icon-message-circle.png
  src/assets/images/icon-notice-fill.png
  src/assets/images/icon-notice.png
  src/components/atoms/Button/CategoryButton/CategoryButton.jsx
  src/components/atoms/P/Feed/FeedText.jsx
  src/components/atoms/Wrapper/DefaultWrapper.jsx
  src/components/molecules/CategoryButtonBox/CategoryButtonBox.jsx
  src/components/molecules/CategoryButtonBox/styled.jsx
  src/components/organisms/TabMenu/TabMenu.jsx
  src/components/organisms/TabMenu/styled.jsx
  src/components/template/CategoryTemplate/CategoryTemplate.jsx
  src/components/template/CategoryTemplate/styled.jsx
  src/components/template/HomeTemplate/HomeTemplate.jsx
  src/components/template/HomeTemplate/styled.jsx
  src/index.css
  src/index.jsx
  src/pages/CategoryPage/CategoryPage.jsx
  src/pages/Home/Home.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/styles/Globalstyled.jsx
Labels: React, 스타일링, 레이아웃

#22 Feature/메인홈및카테고리게시판 #21
  .prettierignore
  .prettierrc.js
  package-lock.json
  package.json
  src/App.jsx
  src/assets/images/icon-more-vertical.png
  src/components/atoms/Wrapper/DefaultWrapper.jsx
  src/components/atoms/Wrapper/HeaderWrapper.jsx
  src/components/atoms/Wrapper/MainWrapper.jsx
  src/components/molecules/CategoryButtonBox/CategoryButtonBox.jsx
  src/components/molecules/TopNavBar/TopNavBar.jsx
  src/components/molecules/TopNavBar/styled.jsx
  src/components/molecules/UserProfile/UserProfileMore.jsx
  src/components/template/CategoryTemplate/CategoryTemplate.jsx
  src/components/template/CategoryTemplate/styled.jsx
  src/components/template/HomeTemplate/HomeTemplate.jsx
  src/components/template/HomeTemplate/styled.jsx
  src/index.jsx
  src/pages/CategoryPage/CategoryPage.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/Login/Login.jsx
  src/styles/Globalstyled.jsx
Labels: 기능구현, React, 스타일링, UI/UX, 레이아웃

#23 Feat : 자유게시판 피드템플릿에 tabmenu 컴포넌트 추가
  src/components/template/FeedTemplate/FeedTemplate.jsx
  src/components/template/FeedTemplate/styled.jsx
Labels: 스타일링, UI/UX, 레이아웃

#19 Feature/splash 스플래쉬 스크린 레이아웃&css 구현
  src/assets/images/splash-background.png
  src/components/molecules/ButtonLoginCard/ButtonLoginCard.jsx
  src/components/molecules/SymbolLogoCard/SymbolLogoCard.jsx
  src/components/molecules/SymbolLogoCard/styled.jsx
  src/components/organisms/SplashView/SplashView.jsx
  src/components/organisms/SplashView/styled.jsx
  src/components/template/SplashTemplate/SplashTemplate.jsx
  src/components/template/SplashTemplate/styled.jsx
  src/pages/SplashPage/SplashPage.jsx
Labels: React, 스타일링, 레이아웃

#26 Feature/메인홈및카테고리게시판 카테고리 별 게시판 데이터 레이아웃 구현 #25
  src/App.jsx
  src/components/molecules/CategoryButtonBox/styled.jsx
  src/components/molecules/CategoryFeedCont/CategoryFeedCont.jsx
  src/components/molecules/CategoryFeedCont/styled.jsx
  src/components/molecules/CategoryUserProfile/CategoryUserProfile.jsx
  src/components/molecules/CategoryUserProfile/styled.jsx
  src/components/molecules/CategoryUserProfileMore/CategoryUserProfileMore.jsx
  src/components/molecules/CategoryUserProfileMore/styled.jsx
  src/components/organisms/CategoryFeedCard/CategoryFeedCard.jsx
  src/components/organisms/CategoryFeedCard/styled.jsx
  src/components/template/CategoryTemplate/CategoryTemplate.jsx
  src/components/template/CategoryTemplate/styled.jsx
  src/components/template/HomeTemplate/HomeTemplate.jsx
  src/components/template/HomeTemplate/styled.jsx
  src/pages/CategoryPage/CategoryPage.jsx
Labels: 기능구현, React, 스타일링, UI/UX, 레이아웃

#35 Feat/회원가입
  package-lock.json
  src/App.jsx
  src/api/SignUp/postUserSignUp.js
  src/components/organisms/SignUpForm/SignUpForm.jsx
  src/components/organisms/SignUpForm/styled.jsx
  src/components/template/SignUpTemplate/SignUpTemplate.jsx
  src/components/template/SignUpTemplate/styled.jsx
  src/pages/SignUpPage/SignUpPage.jsx
Labels: 기능구현, 스타일링, 레이아웃

#33 Feature/splash 스플래쉬 스크린 로그인 버튼 창 레이아웃&css 구현
  src/App.jsx
  src/assets/images/login-button-background.png
  src/components/atoms/Star/Star.jsx
  src/components/molecules/ButtonLoginCard/ButtonLoginCard.jsx
  src/components/molecules/LoginButtonCard/LoginButtonCard.jsx
  src/components/molecules/LoginButtonCard/styled.jsx
  src/components/molecules/StarCard/StarCard.jsx
  src/components/molecules/StarCard/styled.jsx
  src/components/molecules/SymbolLogoCard/SymbolLogoCard.jsx
  src/components/molecules/SymbolLogoCard/styled.jsx
  src/components/organisms/LoginButtonForm/LoginButtonForm.jsx
  src/components/organisms/LoginButtonForm/styled.jsx
  src/components/organisms/SplashView/SplashView.jsx
  src/components/organisms/SplashView/styled.jsx
  src/components/template/LoginButtonTemplate/LoginButtonTemplate.jsx
  src/components/template/LoginButtonTemplate/styled.jsx
  src/pages/SplashPage/SplashPage.jsx
Labels: React, 스타일링, 레이아웃

#28 Feature/자유게시판 팔로워 게시글 목록 기능 구현 및 스타일링 수정, 자유게시판 상세페이지 구현
  src/api/comment/deleteComment.js
  src/api/comment/getCommentList.js
  src/api/comment/postCommentWrite.js
  src/api/feed/deleteLiked.js
  src/api/feed/getFollowFeed.js
  src/api/feed/getFollowFeedDetail.js
  src/api/feed/postLiked.js
  src/api/user/getUserInfo.js
  src/components/molecules/CommentInput/CommentInput.jsx
  src/components/molecules/CommentInput/styled.jsx
  src/components/molecules/FeedCont/FeedCont.jsx
  src/components/molecules/FeedCont/styled.jsx
  src/components/molecules/FeedMoreIcon/FeedMoreIcon.jsx
  src/components/molecules/UserProfile/UserCommentProfile.jsx
  src/components/molecules/UserProfile/UserCommentProfileMore.jsx
  src/components/molecules/UserProfile/UserProfile.jsx
  src/components/molecules/UserProfile/UserProfileMore.jsx
  src/components/molecules/UserProfile/styled.jsx
  src/components/organisms/CommentItem/CommentItem.jsx
  src/components/organisms/CommentItem/styled.jsx
  src/components/organisms/FeedCard/FeedCard.jsx
  src/components/organisms/TabMenu/TabMenu.jsx
  src/components/template/FeedTemplate/FeedDetailTemplate.jsx
  src/components/template/FeedTemplate/FeedTemplate.jsx
  src/components/template/FeedTemplate/styled.jsx
  src/pages/FeedPage/FeedDetailPage.jsx
  src/pages/FeedPage/FeedPage.jsx
Labels: 기능구현, React, 스타일링

#46 Feature/채팅 레이아웃&css구현
  src/App.jsx
  src/components/atoms/Span/ChatText.jsx
  src/components/molecules/ChatBubbleCont/ChatBubbleCont.jsx
  src/components/molecules/ChatBubbleCont/styled.jsx
  src/components/molecules/ChatUserCard/ChatUserCard.jsx
  src/components/molecules/ChatUserCard/styled.jsx
  src/components/molecules/TopNavBar/TopNavBar.jsx
  src/components/molecules/TopNavBar/styled.jsx
  src/components/organisms/ChatBubbleCard/IBubbleCard/IBubbleCard.jsx
  src/components/organisms/ChatBubbleCard/IBubbleCard/styled.jsx
  src/components/organisms/ChatBubbleCard/YouBubbleCard/YouBubbleCard.jsx
  src/components/organisms/ChatBubbleCard/YouBubbleCard/styled.jsx
  src/components/organisms/ChatInput/ChatInput.jsx
  src/components/organisms/ChatInput/styled.jsx
  src/components/template/ChatTemplate/ChatTemplate.jsx
  src/components/template/ChatTemplate/styled.jsx
  src/components/template/ChatUserTemplate/ChatUserTemplate.jsx
  src/components/template/ChatUserTemplate/styled.jsx
  src/pages/ChatPage/ChatDetailPage.jsx
  src/pages/ChatPage/ChatPage.jsx
Labels: React, 스타일링, 레이아웃

#52 Feature/채팅 모달 및 input 전송 버튼 활성화 구현
  src/components/organisms/ChatInput/ChatInput.jsx
  src/components/organisms/ChatInput/styled.jsx
  src/components/template/ChatUserTemplate/ChatUserTemplate.jsx
  src/pages/ChatPage/ChatDetailPage.jsx
Labels: 기능구현, React, 스타일링

#36 Feat : 프로필설정 레이아웃/기능구현
  src/App.jsx
  src/api/ProfileSetting/postAccountNameValid.js
  src/api/ProfileSetting/postProfileImg.js
  src/api/ProfileSetting/postProfileInfo.js
  src/components/organisms/ProfileSettingForm/ProfileSettingForm.jsx
  src/components/organisms/ProfileSettingForm/styled.jsx
  src/components/template/ProfileSettingTemplate/ProfileSettingTemplate.jsx
  src/components/template/ProfileSettingTemplate/styled.jsx
  src/components/template/SignUpTemplate/styled.jsx
  src/pages/ProfileSettingPage/ProfileSettingPage.jsx
  src/pages/SignUpPage/SignUpPage.jsx
  src/styles/Globalstyled.jsx
Labels: 기능구현, 스타일링, 레이아웃

#49 Feature/자유게시판 게시판 상세페이지 레이아웃 & 기능구현
  src/api/comment/postCommentReport.js
  src/api/feed/deletePost.js
  src/api/feed/postPostReport.js
  src/components/molecules/Alert/Alert.jsx
  src/components/molecules/Alert/styled.jsx
  src/components/molecules/Modal/Modal.jsx
  src/components/molecules/Modal/styled.jsx
  src/components/molecules/TopNavBar/TopNavBar.jsx
  src/components/molecules/TopNavBar/styled.jsx
  src/components/molecules/UserProfile/UserCommentProfileMore.jsx
  src/components/molecules/UserProfile/UserProfileMore.jsx
  src/components/organisms/CommentItem/CommentItem.jsx
  src/components/organisms/FeedCard/FeedCard.jsx
  src/components/organisms/FeedCard/styled.jsx
  src/components/template/FeedTemplate/FeedDetailTemplate.jsx
  src/components/template/FeedTemplate/FeedTemplate.jsx
  src/pages/FeedPage/FeedDetailPage.jsx
  src/pages/FeedPage/FeedPage.jsx
Labels: 기능구현, 스타일링, 레이아웃

#48 Feat/타이머
  src/App.jsx
  src/components/organisms/TimerForm/TimerForm.jsx
  src/components/organisms/TimerForm/styled.jsx
  src/components/template/TimerTemplate/TimerTemplate.jsx
  src/components/template/TimerTemplate/styled.jsx
  src/pages/CategoryPage/CategoryDetailPage.jsx
  src/pages/CategoryPage/CategoryPostPage.jsx
  src/pages/TimerPage/TimerPage.jsx
Labels: 기능구현, React, 스타일링, UI/UX, 레이아웃
