Repository TEAM-INFINITE/Dawn-WithMe, pull requests merged in 2023-01, with the labels that each got.

#68 Feature/자유게시판 머지 불가 에러 확인 , 자유게시판 유저 검색 기능 구현
  src/App.jsx
  src/api/search/getSearchUser.js
  src/components/molecules/SearchCard/SearchCard.jsx
  src/components/molecules/SearchCard/styled.jsx
  src/components/molecules/TopNavBar/TopNavBar.jsx
  src/components/molecules/TopNavBar/styled.jsx
  src/components/organisms/FeedCard/FeedCard.jsx
  src/components/template/SearchTemplate/SearchTemplate.jsx
  src/components/template/SearchTemplate/styled.jsx
  src/pages/SearchPage/SearchPage.jsx
Labels: 기능구현, 스타일링, UI/UX, 레이아웃

#57 Feature/splash 템플릿 합치기 및 애니메이션 추가
  src/components/atoms/Wrapper/FullWrapper.jsx
  src/components/molecules/SymbolLogoCard/SymbolLogoCard.jsx
  src/components/molecules/SymbolLogoCard/styled.jsx
  src/components/organisms/LoginButtonForm/LoginButtonForm.jsx
  src/components/organisms/LoginButtonForm/styled.jsx
  src/components/organisms/SplashView/SplashView.jsx
  src/components/organisms/SplashView/styled.jsx
  src/components/template/LoginButtonTemplate/LoginButtonTemplate.jsx
  src/components/template/LoginButtonTemplate/styled.jsx
  src/components/template/SplashTemplate/LoginButtonTemplate.jsx
  src/components/template/SplashTemplate/SplashTemplate.jsx
  src/components/template/SplashTemplate/styled.jsx
  src/pages/SplashPage/SplashPage.jsx
Labels: React, 스타일링, 수정

#72 Feature/자유게시판 게시물 업로드 레이아웃 & 기능 구현
  .eslintrc.js
  src/App.jsx
  src/components/atoms/Textarea/Textarea.jsx
  src/components/molecules/FeedImgBox/FeedImgBox.jsx
  src/components/molecules/FeedImgBox/styled.jsx
  src/components/molecules/TopNavBar/styled.jsx
  src/components/template/FeedTemplate/FeedTemplate.jsx
  src/components/template/FeedUploadTeplate/FeedUploadTemplate.jsx
  src/components/template/FeedUploadTeplate/styled.jsx
  src/pages/FeedUploadPage/FeedUploadPage.jsx
Labels: 기능구현, 스타일링, UI/UX, 레이아웃

#78 Feature/자유게시판 게시물 업로드 기능 구현
  src/api/feed/createFeedPost.js
  src/api/imgUpload/postImages.js
  src/assets/images/icon-delete.png
  src/components/molecules/FeedCont/FeedCont.jsx
  src/components/molecules/FeedCont/styled.jsx
  src/components/molecules/FileUpload/FileUpload.jsx
  src/components/molecules/FileUpload/styled.jsx
  src/components/template/FeedTemplate/FeedTemplate.jsx
  src/components/template/FeedUploadTeplate/FeedUploadTemplate.jsx
  src/components/template/FeedUploadTeplate/styled.jsx
  src/pages/FeedUploadPage/FeedUploadPage.jsx
Labels: 기능구현

#65 Feat/우리동네 스터디카페 지도 레이아웃 및 기능 구현
  public/index.html
  src/assets/images/category-map.png
  src/components/molecules/CategoryButtonBox/CategoryButtonBox.jsx
  src/components/molecules/CategoryButtonBox/styled.jsx
  src/components/organisms/CategoryMapCard/CategoryMapCard.jsx
  src/components/organisms/CategoryMapCard/MapContainer/MapContainer.jsx
  src/components/organisms/CategoryMapCard/MapContainer/styled.jsx
  src/components/organisms/CategoryMapCard/SearchMap/SearchMap.jsx
  src/components/organisms/CategoryMapCard/SearchMap/styled.jsx
  src/components/organisms/CategoryMapCard/styled.jsx
  src/components/template/HomeTemplate/HomeTemplate.jsx
Labels: 기능구현, React, 스타일링, 레이아웃

#80 Feature/자유게시판 오류 수정 및 내 게시글 수정 기능 구현
  src/App.jsx
  src/api/feed/getFeedDetail.js
  src/assets/images/icon-heart.png
  src/assets/images/icon-message-circle.png
  src/components/molecules/Alert/Alert.jsx
  src/components/molecules/FeedCont/FeedCont.jsx
  src/components/molecules/FeedCont/styled.jsx
  src/components/molecules/UserProfile/UserProfileMore.jsx
  src/components/organisms/FeedCard/FeedCard.jsx
  src/components/organisms/ProfileFeedListCard/ProfileFeedListCard.jsx
  src/components/template/EditFeedTemplate/EditFeedTemplate.jsx
  src/components/template/EditFeedTemplate/styled.jsx
  src/components/template/FeedTemplate/FeedTemplate.jsx
  src/components/template/MyProfileTemplate/MyProfileTemplate.jsx
  src/pages/EditFeedPage/EditFeedPage.jsx
  src/pages/FeedPage/FeedDetailPage.jsx
  src/pages/FeedPage/FeedPage.jsx
  src/pages/ProfilePage/MyProfilePage.jsx
Labels: 기능구현, Error, 스타일링, UI/UX, 레이아웃, 수정

#84 Fix : 홈템플릿 맵 검색창 중복 제거
  src/components/template/HomeTemplate/HomeTemplate.jsx
Labels: 수정

#98 Feature/splash 스플래쉬 반응형 구현
  src/components/molecules/SplashLogoCard/SplashLogoCard.jsx
  src/components/molecules/SplashLogoCard/styled.jsx
  src/components/organisms/LoginButtonForm/styled.jsx
  src/components/organisms/SplashView/SplashView.jsx
  src/components/organisms/SplashView/styled.jsx
  src/components/template/SplashTemplate/LoginButtonTemplate.jsx
  src/components/template/SplashTemplate/styled.jsx
Labels: 레이아웃, 수정, 리팩터링

#101 Feature/자유게시판 모바일에서의 너비 오류 수정, 상세 피드에서 댓글 클릭 시 프로필 이동 기능 구현
  src/components/molecules/UserProfile/UserCommentProfileMore.jsx
  src/components/molecules/UserProfile/styled.jsx
Labels: 스타일링, 수정
